# Generated by Django 4.1.13 on 2024-01-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantdetails',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
