# Generated by Django 4.1.13 on 2024-01-27 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0003_consultantdetails_consultant_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_id', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Viewed')], default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.studentdetails')),
            ],
        ),
    ]
