# Generated by Django 4.1.13 on 2024-02-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0004_consultantstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=125, null=True, unique=True),
        ),
    ]
