# Generated by Django 4.1.13 on 2024-02-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0005_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
