# Generated by Django 4.1.13 on 2024-02-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0006_alter_students_created_at_alter_students_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_id', models.IntegerField()),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_id', models.IntegerField()),
                ('exp_title', models.CharField(blank=True, max_length=500, null=True)),
                ('exp_des', models.TextField(blank=True, null=True)),
                ('exp_img', models.ImageField(blank=True, null=True, upload_to='explanation/')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customizes',
            name='benefit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
