# Generated by Django 4.1.13 on 2024-02-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0007_clients_explanation_customizes_benefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='client_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
