# Generated by Django 4.1.13 on 2024-02-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0008_clients_client_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='rate_added_to',
            field=models.BigIntegerField(),
        ),
    ]
