# Generated by Django 4.1.13 on 2024-02-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0009_alter_rates_rate_added_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
