# Generated by Django 4.1.13 on 2024-02-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0010_alter_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitywise',
            name='uw_university_id',
        ),
        migrations.AddField(
            model_name='universitywise',
            name='uw_university_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Acive'), (2, 'Verified')], default=0),
        ),
    ]
