# Generated by Django 4.1.13 on 2024-02-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0012_alter_results_higher_certificate_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='consultant_images/'),
        ),
    ]
