# Generated by Django 4.1.13 on 2024-02-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0013_alter_consultantimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantdetails',
            name='consultant_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
