# Generated by Django 4.1.13 on 2024-03-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0014_alter_consultantdetails_consultant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homefeedback',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
