# Generated by Django 4.1.13 on 2024-03-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0015_homefeedback_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantdetails',
            name='consultant_img',
            field=models.ImageField(blank=True, null=True, upload_to='consultant_images/'),
        ),
        migrations.AlterField(
            model_name='consultantdetails',
            name='consultant_logo',
            field=models.ImageField(blank=True, null=True, upload_to='consultant_logo/'),
        ),
    ]
