# Generated by Django 4.1.13 on 2024-03-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0016_alter_consultantdetails_consultant_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homefeedback',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
