# Generated by Django 4.1.13 on 2024-03-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0017_homefeedback_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantdetails',
            name='consultant_bio',
            field=models.TextField(blank=True, db_column='consultant_bio', null=True),
        ),
        migrations.AlterField(
            model_name='consultantdetails',
            name='consultant_description',
            field=models.TextField(blank=True, db_column='consultant_description', null=True),
        ),
        migrations.AlterField(
            model_name='consultantdetails',
            name='consultant_intro',
            field=models.TextField(blank=True, db_column='consultant_intro', null=True),
        ),
    ]
