# Generated by Django 4.1.13 on 2024-03-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0018_alter_consultantdetails_consultant_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantdetails',
            name='consultant_requirement_image',
            field=models.ImageField(blank=True, null=True, upload_to='consultant_requirement/'),
        ),
        migrations.AlterField(
            model_name='consultantdetails',
            name='consultant_bio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='consultantdetails',
            name='consultant_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='consultantdetails',
            name='consultant_intro',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
