# Generated by Django 4.1.13 on 2024-03-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0020_results_course_certificate_copy_results_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='balance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='consultant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
