# Generated by Django 4.1.13 on 2024-03-16 04:10

from django.db import migrations, models
import django.utils.timezone
import visa.models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0021_alter_levels_balance_id_alter_levels_consultant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizes',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customizes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=visa.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='customizes',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
