# Generated by Django 4.1.13 on 2024-03-16 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0022_alter_customizes_created_at_alter_customizes_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantwises',
            name='country_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultants', to='visa.countries'),
        ),
    ]
