# Generated by Django 4.1.13 on 2024-03-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0023_consultantwises_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarships',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
