# Generated by Django 4.1.13 on 2024-03-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0024_scholarships_expiration_time_scholarships_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customizes',
            name='benefit',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
