# Generated by Django 4.1.13 on 2024-03-18 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0025_alter_customizes_benefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MastersDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('result', models.FloatField(blank=True, null=True)),
                ('department', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('enrolled', models.BooleanField(blank=True, default=False, null=True)),
                ('certificate_copy', models.ImageField(blank=True, null=True, upload_to='certificates/')),
            ],
            options={
                'db_table': 'masters degree',
            },
        ),
        migrations.CreateModel(
            name='OtherCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('result', models.FloatField(blank=True, null=True)),
                ('institute', models.CharField(max_length=255)),
                ('passing_year', models.IntegerField(blank=True, null=True)),
                ('enrolled', models.BooleanField(blank=True, default=False, null=True)),
                ('certificate_copy', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.coursename')),
            ],
            options={
                'db_table': 'other_certification',
            },
        ),
    ]
