# Generated by Django 4.1.13 on 2024-03-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0026_coursename_mastersdegree_othercertification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastersdegree',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mastersdegree',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='othercertification',
            name='institute',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='othercertification',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
