# Generated by Django 4.1.13 on 2024-03-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0027_alter_mastersdegree_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersdegree',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastersdegree',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othercertification',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othercertification',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
