# Generated by Django 4.1.13 on 2024-03-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0030_results_phd_results_phd_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantwises',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
