# Generated by Django 4.1.13 on 2024-03-27 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0031_consultantwises_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarships',
            name='country_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='visa.countries'),
        ),
    ]
