# Generated by Django 4.2.11 on 2024-04-02 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0033_results_diploma_results_diploma_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizes',
            name='consultant_id',
        ),
        migrations.AddField(
            model_name='customizes',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
