# Generated by Django 4.2.11 on 2024-04-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0034_remove_customizes_consultant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='level_1',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='level_2',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='level_3',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='level_4',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='level_5',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
