# Generated by Django 4.2.11 on 2024-04-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0035_alter_levels_level_1_alter_levels_level_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastersdegree',
            name='rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othercertification',
            name='rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='course_rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='diploma_rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='higher_rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='phd_rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='secondary_rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='undergraduation_rejection_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
