# Generated by Django 4.2.29 on 2026-03-04 07:50

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0036_mastersdegree_rejection_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('thumbnail_image', models.ImageField(help_text='Image for homepage card', upload_to='services/thumbnails/')),
                ('banner_image', models.ImageField(help_text='Image for detail page hero section', upload_to='services/banners/')),
                ('short_description', models.TextField(help_text='Short description for homepage card (max 200 chars)', max_length=200)),
                ('main_content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Main Content')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visa Service',
                'verbose_name_plural': 'Visa Services',
                'db_table': 'visa_services',
                'ordering': ['-created_at'],
            },
        ),
    ]
