# Generated by Django 4.2.16 on 2026-03-05 06:01

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0037_visaservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visaservice',
            options={},
        ),
        migrations.RemoveField(
            model_name='visaservice',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='visaservice',
            name='main_content',
        ),
        migrations.RemoveField(
            model_name='visaservice',
            name='thumbnail_image',
        ),
        migrations.RemoveField(
            model_name='visaservice',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='visaservice',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visaservice',
            name='image',
            field=models.ImageField(default='', upload_to='services/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visaservice',
            name='subtitle',
            field=models.CharField(default='', help_text="Short detail like 'Subclass 500'", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visaservice',
            name='short_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visaservice',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='visaservice',
            table=None,
        ),
    ]
