# Generated by Django 4.2.16 on 2026-03-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0038_alter_visaservice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
