# Generated by Django 4.2.16 on 2026-03-28 08:57

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0039_otprequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otprequest',
            options={'ordering': ['-timestamp'], 'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.CreateModel(
            name='SelfFundedProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_fee', models.CharField(max_length=100)),
                ('requirements', django_ckeditor_5.fields.CKEditor5Field()),
                ('foreign_student_policy', django_ckeditor_5.fields.CKEditor5Field()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='self_funded_programs', to='visa.countries')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_funded_programs', to='visa.university')),
            ],
            options={
                'verbose_name': 'Self Funded Program',
                'verbose_name_plural': 'Self Funded Programs',
                'ordering': ['-created_at'],
            },
        ),
    ]
