# Generated by Django 4.2.16 on 2026-03-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0040_alter_otprequest_options_selffundedprogram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversityWise',
        ),
    ]
