# Generated by Django 4.2.16 on 2026-03-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0041_delete_universitywise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='countries',
            new_name='country',
        ),
    ]
