# Generated by Django 4.2.16 on 2026-03-29 09:55

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0042_rename_countries_university_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_steps', to='visa.countries')),
            ],
            options={
                'db_table': 'scholarship_steps',
                'ordering': ['step_number'],
            },
        ),
    ]
