# Generated by Django 4.2.16 on 2026-04-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0043_scholarshipstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Student Visa BD', max_length=100)),
                ('meta_title', models.CharField(help_text='Default browser tab title', max_length=255)),
                ('meta_description', models.TextField(help_text='SEO description for search engines')),
                ('meta_keywords', models.TextField(help_text='Comma separated keywords')),
                ('og_image', models.ImageField(blank=True, help_text='Social media sharing image 1200x630', null=True, upload_to='seo/og/')),
                ('google_verification_id', models.CharField(blank=True, help_text='Google Search Console ID', max_length=255, null=True)),
                ('analytics_code', models.TextField(blank=True, help_text='Google Analytics or Facebook Pixel script', null=True)),
                ('asset_version', models.CharField(default='1.0', help_text='Version for CSS/JS cache busting (e.g. ?v=1.0)', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
