# Generated by Django 4.2.16 on 2026-04-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0044_seosettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaKeywordPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='meta_description',
            field=models.TextField(help_text='SEO description for search engines', max_length=150),
        ),
        migrations.AlterField(
            model_name='seosettings',
            name='meta_title',
            field=models.CharField(help_text='Default browser tab title', max_length=60),
        ),
    ]
