# Generated by Django 4.2.16 on 2026-04-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0046_pageseosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantdetails',
            name='consultant_linkedin',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='consultantdetails',
            name='consultant_youtube',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
