# Generated by Django 4.2.16 on 2026-04-13 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0047_consultantdetails_consultant_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopConsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='top_featured', to='visa.users')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
