# Generated by Django 4.2.16 on 2026-04-19 05:52

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0048_topconsultant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otprequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.RemoveField(
            model_name='university',
            name='established_date',
        ),
        migrations.AddField(
            model_name='university',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='university_logo',
            field=models.ImageField(blank=True, null=True, upload_to='university_logos/'),
        ),
        migrations.AlterField(
            model_name='university',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universities_new', to='visa.countries'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='university',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='UniversityWiseScholarship',
            fields=[
                ('uws_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='university_scholarships/')),
                ('apply_procedure', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Apply Procedure')),
                ('visa_requirements', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Visa Requirements')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Scholarship Description')),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarships', to='visa.university')),
            ],
            options={
                'verbose_name': 'University Wise Scholarship',
                'verbose_name_plural': 'University Wise Scholarships',
                'db_table': 'university_wise_scholarships',
            },
        ),
    ]
