# Generated by Django 4.2.16 on 2026-04-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0049_alter_otprequest_options_alter_university_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizes',
            name='cta_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customizes',
            name='cta_target',
            field=models.CharField(choices=[('_self', 'Same Window'), ('_blank', 'New Window')], default='_self', max_length=20),
        ),
        migrations.AddField(
            model_name='customizes',
            name='cta_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customizes',
            name='eyebrow_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customizes',
            name='overlay_style',
            field=models.CharField(choices=[('frosted', 'Frosted Island'), ('gradient', 'Gradient Fade'), ('none', 'None')], default='frosted', max_length=20),
        ),
        migrations.AddField(
            model_name='customizes',
            name='serial_order',
            field=models.IntegerField(default=10, help_text='Determine display sequence (10, 20, 30...)'),
        ),
        migrations.AddField(
            model_name='customizes',
            name='text_color_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=10),
        ),
        migrations.AddField(
            model_name='customizes',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customizes',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
